apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
    - git:
        repoURL: https://github.com/openstack/openstack-helm.git
        revision: 2025.2.0
        directories:
          - path: mariadb
            values:
              labels:
                server:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                ingress:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                prometheus_mysql_exporter:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                error_server:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                job:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                test:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64


              volume:
                enabled: true
                class_name: "longhorn"         
              pod:
                replicas:
                  server: 1
                
          - path: memcached
            values:
              labels:
                server:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64            
          - path: rabbitmq
            values:
              labels:
                server:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                prometheus_rabbitmq_exporter:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                test:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
                jobs:
                  node_selector_key: kubernetes.io/arch
                  node_selector_value: amd64
              volume:
                enabled: true      
                class_name: "longhorn"   
              pod:
                replicas:
                  server: 1

              manifests:
                ingress_api: false
                ingress_management: false
                service_ingress_management: false



  generators:
    - list:
        elements:
          # Chaque élément représente une Application
          - app: mariadb
          - app: memcached
          - app: rabbitmq

  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default

      sources:
        # Chart Helm principal
        - repoURL: https://github.com/openstack/openstack-helm.git
          targetRevision: '{{targetRevision | default "2025.2.0"}}'
          path: {{app}}
          helm:
            # Surcharge des valeurs Helm
            values:
              - image.tag: '{{extraValues.imageTag | default "latest"}}'
              - replicaCount: '{{extraValues.replicas | default 1}}'

        # Repo contenant les values.yaml
        - repoURL: https://github.com/org/config-repo.git
          targetRevision: main
          ref: valuesRepo

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace | default openstack}}'  # namespace dynamique

      # -------------------------
      # Synchronisation automatique
      # -------------------------
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
